[build]
  command = "mvn clean package"
  publish = "target/classes/static"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  JAVA_VERSION = "17"
  MAVEN_VERSION = "3.9.5" 