[build]
  base = "."
  command = "./mvnw clean package"
  publish = "target/classes/static"

[build.environment]
  JAVA_VERSION = "17"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 